// examples/react-showcase/src/App.tsx
import {
  View,
  TextInput,
  Code,
  Markdown,
  Canvas,
  VirtualList,
  MotionView,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
  Combobox,
  ComboboxInput,
  ComboboxContent,
  ComboboxList,
  ComboboxItem,
  ComboboxEmpty,
  useTextSearch,
  useGpuiTimeline,
  type StyleDesc,
} from "@gpui-native/react"
import { useState } from "react"
const panel: StyleDesc = {
  padding: 16,
  gap: 10,
  borderRadius: 10,
  backgroundColor: "#1e293b",
  display: "flex",
  flexDirection: "column",
}
export default function App() {
  const [query, setQuery] = useState("native")
  const search = useTextSearch({ query })
  const timeline = useGpuiTimeline()
  return (
    <View
      style={{
        width: "100%",
        height: "100%",
        padding: 24,
        gap: 16,
        display: "flex",
        flexDirection: "column",
        overflow: "scroll",
        backgroundColor: "#0f172a",
        color: "#e2e8f0",
      }}
    >
      <text style={{ fontSize: 28, fontWeight: 700 }}>React × GPUI</text>
      <div style={panel}>
        <Tooltip>
          <TooltipTrigger style={{ cursor: "pointer" }}>
            Hover or focus for a native tooltip
          </TooltipTrigger>
          <TooltipContent style={{ padding: 12 }}>React state, GPUI positioning</TooltipContent>
        </Tooltip>
        <Select defaultValue="react">
          <SelectTrigger style={{ padding: 10 }}>
            <SelectValue />
          </SelectTrigger>
          <SelectContent style={{ padding: 12 }}>
            <SelectItem value="react">React</SelectItem>
            <SelectItem value="vue">Vue</SelectItem>
            <SelectItem value="future" disabled>
              More adapters soon
            </SelectItem>
          </SelectContent>
        </Select>
        <Combobox
          items={["Canvas", "Code", "Markdown", "Virtual list", "Native text"]}
          autoHighlight
        >
          <ComboboxInput placeholder="Find a component" style={{ padding: 12 }} />
          <ComboboxContent style={{ padding: 12 }}>
            <ComboboxList>
              {(item) => (
                <ComboboxItem
                  key={item}
                  value={item}
                  style={({ highlighted }) => ({
                    padding: 8,
                    backgroundColor: highlighted ? "#334155" : "#1e293b",
                  })}
                >
                  {item}
                </ComboboxItem>
              )}
            </ComboboxList>
            <ComboboxEmpty>No matches</ComboboxEmpty>
          </ComboboxContent>
        </Combobox>
      </div>
      <div style={panel}>
        <TextInput
          value={query}
          onChange={(event) => setQuery(event.value ?? "")}
          placeholder="Search text"
        />
        <div {...search.props}>
          <Markdown
            source={
              "# Native text\nReact uses the same native selection and search pipeline as Vue."
            }
          />
        </div>
        <div onClick={search.next}>Next match ({search.total})</div>
      </div>
      <Code
        code={"function App() {\n  return <text>Hello, native world</text>\n}"}
        language="tsx"
        style={panel}
      />
      <Canvas
        style={{ height: 90 }}
        commands={[
          { type: "rect", x: 0, y: 0, width: 160, height: 70, radius: 12, fill: "#38bdf8" },
          { type: "circle", cx: 210, cy: 35, radius: 30, fill: "#a78bfa" },
        ]}
      />
      <MotionView
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1 }}
        style={panel}
      >
        Native motion, with no React updates per frame
      </MotionView>
      <div onClick={() => timeline.pause()}>Pause timeline</div>
      <div onClick={() => timeline.play()}>Resume timeline</div>
      <VirtualList estimatedItemHeight={30} style={{ height: 160 }}>
        {Array.from({ length: 100 }, (_, i) => (
          <text key={i} style={{ height: 30 }}>
            Native row {i + 1}
          </text>
        ))}
      </VirtualList>
    </View>
  )
}

// examples/svelte-showcase/src/App.svelte
<script lang="ts">
  import {
    Button,
    Column,
    View,
    Row,
    Text,
    TextInput,
    Code,
    Markdown,
    Canvas,
    VirtualList,
    MotionView,
    Select,
    SelectTrigger,
    SelectValue,
    SelectContent,
    SelectItem,
    Combobox,
    ComboboxInput,
    ComboboxContent,
    ComboboxItem,
    ComboboxEmpty,
    Tooltip,
    TooltipTrigger,
    TooltipContent,
    useTextSearch,
  } from "@gpui-native/svelte";
  let language = $state("typescript"),
    fruit = $state(""),
    query = $state("native");
  const search = useTextSearch(() => ({ query }));
  const panel = { padding: 12, background: "#1e293b", borderRadius: 8 };
</script>

<Column
  style={{
    width: "100%",
    height: "100%",
    padding: 24,
    gap: 12,
    background: "#111827",
    color: "#f8fafc",
    overflow: "scroll",
  }}
>
  <Text style={{ fontSize: 28 }}>Svelte native components</Text>
  <Row style={{ gap: 16 }}>
    <Tooltip
      ><TooltipTrigger style={panel}>Hover or focus</TooltipTrigger
      ><TooltipContent style={panel}>A native GPUI tooltip</TooltipContent
      ></Tooltip
    >
    <Select bind:value={language}
      ><SelectTrigger style={panel}><SelectValue /></SelectTrigger
      ><SelectContent style={panel}
        ><SelectItem value="typescript" textValue="TypeScript"
          >TypeScript</SelectItem
        ><SelectItem value="rust" textValue="Rust">Rust</SelectItem
        ></SelectContent
      ></Select
    >
    <Combobox bind:value={fruit}
      ><ComboboxInput placeholder="Find fruit" style={panel} /><ComboboxContent
        style={panel}
        ><ComboboxItem value="apple" textValue="Apple">Apple</ComboboxItem
        ><ComboboxItem value="banana" textValue="Banana">Banana</ComboboxItem
        ><ComboboxEmpty>Nothing found</ComboboxEmpty></ComboboxContent
      ></Combobox
    >
  </Row>
  <Code
    code={language === "rust" ? "let count = 42;" : "let count = $state(42)"}
    {language}
    style={panel}
  />
  <Row style={{ gap: 8 }}
    ><TextInput
      bind:value={query}
      placeholder="Search native text"
      style={panel}
    /><Button onPress={() => search.next()} style={panel}
      >Next match ({search.total})</Button
    ></Row
  >
  <View {...search.props} style={panel}>
    <Text>Native text uses GPUI selection and native highlighting.</Text>
  </View>
  <Markdown
    source={"# Markdown\nSvelte owns reactivity. GPUI owns **text, layout and paint**."}
    style={panel}
  />
  <Canvas
    commands={[
      { type: "rect", x: 0, y: 0, width: 180, height: 40, fill: "#60a5fa" },
    ]}
    style={{ height: 48, flexShrink: 0 }}
  />
  <MotionView
    initial={{ opacity: 0, left: -20 }}
    animate={{ opacity: 1, left: 0 }}
    transition={{ duration: 0.5 }}
    ><Text>Animation runs in GPUI</Text></MotionView
  >
  <VirtualList estimatedItemHeight={28} style={{ height: 180, flexShrink: 0 }}
    >{#each Array.from({ length: 1000 }, (_, i) => i) as id (id)}<Text
        style={{ height: 28 }}>Native row {id}</Text
      >{/each}</VirtualList
  >
</Column>
