// examples/svelte-webgpu/src/App.svelte
<script lang="ts">
  import { Canvas, Column, Text, useGPUCanvas } from "@gpui-native/svelte";
  import { startWebGPUScene } from "../../shared/webgpu-scene.js";
  let { gpu }: { gpu: GPU } = $props();
  const canvas = useGPUCanvas(() => ({ width: 640, height: 400 }));
  let error = $state("");
  $effect(() => {
    const current = canvas.current;
    if (!current) return;
    let cancelled = false,
      stop: (() => void) | undefined;
    async function start() {
      try {
        const dispose = await startWebGPUScene(
          current!,
          gpu,
          (next) => (error = String(next)),
        );
        if (cancelled) dispose();
        else stop = dispose;
      } catch (next) {
        if (!cancelled) error = String(next);
      }
    }
    void start();
    return () => {
      cancelled = true;
      stop?.();
    };
  });
</script>

<Column
  style={{
    width: "100%",
    height: "100%",
    padding: 24,
    gap: 16,
    background: "#111827",
    color: "#f8fafc",
  }}
  ><Text>Svelte runes + WebGPU</Text>{#if canvas.current}<Canvas
      source={canvas.current.id}
      style={{ width: 640, height: 400 }}
    />{/if}{#if error}<Text>{error}</Text>{/if}</Column
>

// examples/react-webgpu/src/App.tsx
import { GpuiCanvas, useGPUCanvas } from "@gpui-native/react"
import { useEffect, useState } from "react"

import { startWebGPUScene } from "../../shared/webgpu-scene.js"

export default function App({ gpu }: { gpu: GPU }) {
  const canvas = useGPUCanvas({ width: 640, height: 400 })
  const [error, setError] = useState("")
  useEffect(() => {
    if (!canvas) return
    let cancelled = false
    let stop: (() => void) | undefined
    void startWebGPUScene(canvas, gpu, (error) => setError(String(error)))
      .then((dispose) => {
        if (cancelled) dispose()
        else stop = dispose
      })
      .catch((error) => {
        if (!cancelled) setError(String(error))
      })
    return () => {
      cancelled = true
      stop?.()
    }
  }, [canvas, gpu])
  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        padding: 24,
        gap: 16,
        flexDirection: "column",
        backgroundColor: "#070b17",
        color: "#e8efff",
      }}
    >
      <text style={{ fontSize: 26 }}>React · WebGPU canvas</text>
      <text>WGSL shaders · 4× antialiasing · bounded asynchronous presentation</text>
      {canvas && (
        <GpuiCanvas
          source={canvas.id}
          testId="webgpu-canvas"
          style={{ width: 640, height: 400 }}
          commands={[
            {
              type: "rect",
              x: 12,
              y: 12,
              width: 616,
              height: 376,
              radius: 12,
              stroke: "#6686b0",
              strokeWidth: 1,
            },
          ]}
        />
      )}
      {error && <text style={{ color: "#ff8888" }}>{error}</text>}
    </div>
  )
}
