// examples/counter/src/App.vue
<script setup lang="ts">
import {
  Button,
  Column,
  Text,
  Code,
  TextInput,
  MotionView,
  type MotionStyle,
  type MotionTransition,
  type StyleDesc,
} from "@gpui-native/vue"
import { ref } from "vue"

const palette = {
  background: "#10131a",
  panel: "#191e29",
  text: "#eef2ff",
  muted: "#98a2b3",
  accent: "#7c9cff",
}

const count = ref(0)
const label = ref("Counter")

const rootStyle: StyleDesc = {
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  width: "100%",
  height: "100%",
  gap: 18,
  padding: 32,
  background: palette.background,
  color: palette.text,
  overflow: "scroll",
}

const cardStyle: StyleDesc = {
  position: "relative",
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  gap: 14,
  padding: 26,
  width: "100%",
  maxWidth: 396,
  flexShrink: 0,
  background: palette.panel,
  borderRadius: 16,
  borderWidth: 1,
  borderColor: "#293044",
}

const inputStyle: StyleDesc = {
  width: "100%",
  padding: 10,
  borderRadius: 8,
  borderWidth: 1,
  borderColor: "#3a435a",
  background: "#11151e",
}

const buttonStyle: StyleDesc = {
  padding: 12,
  paddingLeft: 20,
  paddingRight: 20,
  borderRadius: 10,
  background: palette.accent,
  color: "#0b1020",
  fontWeight: 700,
  cursor: "pointer",
  hover: { opacity: 0.88 },
  active: { opacity: 0.7 },
}

// <code> is deliberately a bare primitive; the app owns its card surface.
const codeStyle: StyleDesc = {
  width: "100%",
  padding: 12,
  background: "#11151e",
  borderWidth: 1,
  borderColor: "#293044",
  borderRadius: 8,
}

const entrance: MotionStyle = { opacity: 1, top: 0 }
const entranceTransition: MotionTransition = {
  duration: 0.35,
  ease: "easeOut",
}

function increment(): void {
  count.value += 1
}
</script>

<template>
  <Column :style="rootStyle">
    <Text :style="{ fontSize: 30, fontWeight: 700 }">gpui-vue</Text>
    <Text :style="{ color: palette.muted }">Vue 3 reactivity rendered by Zed GPUI</Text>

    <MotionView
      :initial="{ opacity: 0, top: 8 }"
      :animate="entrance"
      :transition="entranceTransition"
      :style="cardStyle"
    >
      <TextInput v-model="label" placeholder="Counter label" :style="inputStyle" />

      <Text testId="count" :style="{ fontSize: 48, fontWeight: 700 }"
        >{{ label }}: {{ count }}</Text
      >

      <Button testId="increment" :style="buttonStyle" @press="increment"> Increment </Button>

      <Code
        :code="`const count = ${count}`"
        language="typescript"
        :showLineNumbers="false"
        :style="codeStyle"
      />
    </MotionView>
  </Column>
</template>

// examples/react-counter/src/App.tsx
import {
  Button,
  Column,
  Row,
  TextInput,
  Text,
  useWindowSize,
  type StyleDesc,
} from "@gpui-native/react"
import { useState } from "react"
const button: StyleDesc = {
  padding: 14,
  backgroundColor: "#30466e",
  borderRadius: 8,
  cursor: "pointer",
}
export default function App() {
  const [count, setCount] = useState(0)
  const [name, setName] = useState("React")
  const size = useWindowSize()
  return (
    <Column
      style={{
        width: "100%",
        height: "100%",
        overflow: "scroll",
        padding: 32,
        gap: 20,
        display: "flex",
        flexDirection: "column",
        backgroundColor: "#111827",
        color: "#f8fafc",
      }}
    >
      <Text style={{ fontSize: 30, fontWeight: 700 }}>Hello, {name}</Text>
      <TextInput
        testId="name"
        value={name}
        onChange={(event) => setName(event.value ?? "")}
        style={{ width: 280, maxWidth: "100%", padding: 12, backgroundColor: "#1e293b" }}
      />
      <Text testId="count" style={{ fontSize: 48 }}>
        {count}
      </Text>
      <Row style={{ gap: 12 }}>
        <Button testId="decrement" style={button} onPress={() => setCount((value) => value - 1)}>
          −
        </Button>
        <Button testId="increment" style={button} onPress={() => setCount((value) => value + 1)}>
          +
        </Button>
        <Button style={button} disabled={count === 0} onPress={() => setCount(0)}>
          Reset
        </Button>
      </Row>
      <Text>
        {size.width} × {size.height} · rendered by GPUI
      </Text>
    </Column>
  )
}
